services:
  project:
    build:
      context: ./
    container_name: silver_frontend
    environment:
      - VITE_API_URL=https://api.project.com
    restart: on-failure
    ports:
      - "3000:3000"
